const SUBMIT_GAME_REQUEST = "SUBMIT_GAME_REQUEST";
const SUBMIT_GAME_SUCCESS = "SUBMIT_GAME_SUCCESS";
const SUBMIT_GAME_FAILURE = "SUBMIT_GAME_FAILURE";

const INIT_GAME_REQUEST = "INIT_GAME_REQUEST";
const INIT_GAME_SUCCESS = "INIT_GAME_SUCCESS";
const INIT_GAME_FAILURE = "INIT_GAME_FAILURE";

const ACCEPT_GAME_REQUEST = "ACCEPT_GAME_REQUEST";
const ACCEPT_GAME_SUCCESS = "ACCEPT_GAME_SUCCESS";
const ACCEPT_GAME_FAILURE = "ACCEPT_GAME_FAILURE";

const UPDATE_GAME_REQUEST = "UPDATE_GAME_REQUEST";
const UPDATE_GAME_SUCCESS = "UPDATE_GAME_SUCCESS";
const UPDATE_GAME_FAILURE = "UPDATE_GAME_FAILURE";

const END_GAME_REQUEST = "END_GAME_REQUEST";
const END_GAME_SUCCESS = "END_GAME_SUCCESS";
const END_GAME_FAILURE = "END_GAME_FAILURE";

export default {
  INIT_GAME_REQUEST,
  INIT_GAME_SUCCESS,
	INIT_GAME_FAILURE,
	SUBMIT_GAME_REQUEST,
	SUBMIT_GAME_SUCCESS,
	SUBMIT_GAME_FAILURE,
	UPDATE_GAME_REQUEST,
  UPDATE_GAME_SUCCESS,
	UPDATE_GAME_FAILURE,
	ACCEPT_GAME_REQUEST,
  ACCEPT_GAME_SUCCESS,
	ACCEPT_GAME_FAILURE,
	END_GAME_REQUEST,
  END_GAME_SUCCESS,
	END_GAME_FAILURE

};
